apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # different name
  name: my-prod-tls
  namespace: default
spec:
  # dedicate secret for the TLS cert
  secretName: my-prod-tls
  issuerRef:
    # referencing the production issuer
    name: letsencrypt-prod
  dnsNames:
  - donaph.ddns.net